### ISSUE TITLE
Process output

### ISSUE THREAD

**Issue by jycouet** [renovateapp/renovate#1232]
Hey, it's me again 😀 

As you heard, in VSTS I created a build task to run renovate on regular basis.
I would like to give a good experience over there with your nice job.

This build task has 3 possible results: `error` `warning` `success`.

How could I get this info from your cli in a nice way?
Any suggestions?

**Comment by rarkins** [comment]
We use the term warning and error towards the user, e.g. an invalid config field will cause an error while a dependency with a github link will warn. On the server side though, I usually map user errors to warnings and user warnings to info messages. My logic is that errors in logs should alert me immediately as something bad has happened (maybe a bug), while warnings are there for me to look at now and then to see if I should alert the user to help them.

The above means it's a little hard right now to extract warning/error from a user perspective.

We have errors and warnings arrays attached to `config` that are passed through and eventually added to PRs if non-empty. Perhaps we can make sure that we log something like "PR has errors" or "PR has warnings" and you can simply search the logs in case any PR had that message and then report accordingly. e.g. if 1 or more errors then result=`error`, else if 1 or more warnings then result=`warning`, else result=`success`.

You have the choice of formatted logs (which you would see today) or json logs. If you expect users to look at the logs then probably sticking with formatted logs is best, but otherwise if you set `LOG_FORMAT=json` in env then each line will be a JSON record instead (easier for parsing).

**Comment by jycouet** [comment]
Thank you for your thoughts.
I'm not a big fan of relying on logs.

But anyway, when there is a PR with an error/warning we already have a comment in this PR. So this it good 👍
