### ISSUE TITLE
Update data security section about commit status permission

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1307]
Hi!

The [data-security GitHub permissions](https://renovateapp.com/docs/all-other/data-security#github-permissions) docs say:

> Read and write access to commit statuses
> ... Write access is requested in addition to facilitate Renovate adding its own commit statuses in future (such as whether an upgrade is unpublishable, stable, etc)

I think the write permission is now used rather than being just reserved for the future?
https://github.com/renovateapp/renovate/blob/7675f3a9f12728b6e5d7c68ac5b0897594a0cfd8/lib/workers/branch/status-checks.js#L38-L44
https://github.com/renovateapp/renovate/blob/4101fa40a6889d26c67ddfd5a049f78bbbb51762/docs/status-checks.md#unpublish-safe

Many thanks :-)

**Comment by rarkins** [comment]
Thanks. Yes, some statuses are now supported although rarely enabled by anybody (they default to disabled).

FYI on a related topic I have created a second Renovate App called Forking Renovate - https://github.com/apps/forking-renovate

It behaves pretty much the same as Renovate except that it operates from its own forks of repositories in order to not request read/write code permissions. As a result it can't automerge anything though. This was at the request of the angular team, as Google policy does not allow apps installed that request write permissions.

**Comment by rarkins** [comment]
Now fixed, thank you

**Comment by edmorley** [comment]
Looks great - thank you.

> FYI on a related topic I have created a second Renovate App called Forking Renovate - https://github.com/apps/forking-renovate

Oh interesting! For mozilla/treeherder I don't see us using the auto-merge feature (given our frontend test coverage is somewhat lacking compared to the backend), so we wouldn't miss that feature. However it might make the "push extra changes to fix a breaking major version bump to the same branch" workflow (that I use currently for eg pyup.io) harder, since even with "allow edits from maintainers" enabled, one has to add the correct upstream and use HTTPS auth not SSH etc.

**Comment by rarkins** [comment]
Good point, I haven't had the need to try editing/updating to fix breaking updates. It would probably be more painful from a fork.
