### ISSUE TITLE
Add [skip ci] to pin dependency PR

### ISSUE THREAD

**Issue by tinovyatkin** [renovateapp/renovate#1319]
`[skip ci]` is supported by majority of CI on the market and will allow to same some resources by not running `pin dependency` PRs on CI (as it makes no sense).

**Comment by rarkins** [comment]
I would support this as an option but not as default behaviour. 

For perspective, pinning is usually done once so quickly becomes only a small fraction of total CI time on a project after Renovate is installed. 

It can also happen that the pin dependencies PR can fail CI even if the previous master commit it was branched off passed. This happens if a direct or indirect dependency release within range broke things since the last commit. By skipping CI you would not be aware of this break until some time later and it would look like Renovate’s fault.

**Comment by tinovyatkin** [comment]
Well, let see from a different perspective - for example, we are on Github model - ie, our `master` is protected branch and our CI _deploys_ everything from `master` after successful builds.

In that case adding whatever new dependency in a PR (or manual upgrade via `yarn upgrade` that breaks pinning) will result in new PR and second deploy from the same codebase.

I think there a lot of use cases for `[skip ci]` like dependencies that for sure will not change code (non fixing linters or  `@type/*` for example or even all devDependencies in some projects) and having an option to always skip CI in that updates will be very useful to unload CI from no-sense builds.

**Comment by rarkins** [comment]
I agree that adding the option to easily skip CI is definitely useful. And via presets we can make the various use cases easy to add as they are discovered.

**Comment by rarkins** [comment]
This can now be accomplished if you add the preset `":pinSkipCi"` to your `extends` array.
