### ISSUE TITLE
Improve UX for closing/ignoring PRs for monorepo updates

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1330]
Hi!

In mozilla/treeherder#3048 (a PR for a updating a handful of React monorepo packages) I closed the PR since I am making the changes in my own PR (as it requires a number of manual changes beyond just bumping the packages). After closing the PR I also deleted the branch (like I've done when ignoring single-package PRs in the past) - however this resulted in a brand new PR being opened (mozilla/treeherder#3068), which wasn't desired.

I'm presuming this is since the monorepo PRs use a branch name/PR title of form `renovate/react-monorepo` and `Update react monorepo packages` respectively, which don't contain a major version number, and so don't allow Renovate to do the same de-duping as performed with single packages.

I'm not sure what the best way might be to improve the UX here - without the version numbers there isn't a good way forwards. Perhaps this needs a combination of:
* identifying if all packages are on the same version number, and if so, including that in the branch name / PR title like for single package PRs
* if the above isn't the case (ie lots of different versions for the packages within the PR), then adding a comment to the PR description warning to not delete the branch after closing the PR?

**Comment by edmorley** [comment]
Ah so it looks like closing the PR is enough to trigger a new PR (even if the old branch is not deleted) - there's now a third PR:
mozilla/treeherder/pull/3069

**Comment by rarkins** [comment]
This particular case you have should be avoided if Renovate (a) checks the "newVersion" in groups to see if they're all the same, and (b) adds the version to the prTitle if so, (c) disabling `recreateClosed` for that branch. For groups, we implicitly set `recreateClosed=true` otherwise the first ever group PR would then block all future ones. But if we have a version number for groups in the PR title then it will kind of "cache bust".

In the meantime, you probably just need to leave the PR open until you complete work elsewhere, and then you should see it autoclosed once master already has the same versions in it.

**Comment by rarkins** [comment]
The other thing we should be doing is using the dependency *name* in the PR title - instead of the group title - if there's only one dependency in the group. e.g. if you have a monorepo with 5 `package.json` files and `expect` from the Jest monorepo is upgraded in all, we should call the PR "Upgrade expect to v22.0.5" or something like that, instead of "Upgrade Jest monorepo packages".

**Comment by rarkins** [comment]
Finally, if there is a group with mixed package names and mixed versions, I don't think there's much we can do, because we need to reuse those branch names and PR titles each time and it's hard for us to know what used to exist without implementing full state, which would be highly undesirable and a fork from the regular CLI too. It might be possible that we allow you to close a PR to "hide" it and keep the branch, and we detect that and don't recreate/reopen the PR.

**Comment by rarkins** [comment]
@edmorley note: I won't push this live to the **app** just yet in case there's any undesirable behaviour change, as I won't be online regularly today to watch the logs carefully.

**Comment by edmorley** [comment]
Yeah that's probably best! Thank you for the PR - and hope you have a good holiday break :-)
