### ISSUE TITLE
Tests fail in some timezones

### ISSUE THREAD

**Issue by jahredhope** [renovateapp/renovate#1353]
Awesome solution, thanks! I was hoping you could help with a problem I had setting up for local development.
The initial test run failed before any code changes, likely due to my **Australian timezone**.

The following tests are failing.
```
workers/branch/schedule › isScheduledNow(config) › approves first day of the month
workers/branch/schedule › isScheduledNow(config) › supports every weekday
workers/branch/schedule › isScheduledNow(config) › supports outside hours
workers/branch/schedule › isScheduledNow(config) › supports before hours true
```
This is with local machine time of **GMT +1100**. When I change to GMT +0 the **tests pass**.

Using `mockdate` to set the timezone offset doesn't seem to help.

# Steps to recreate
1. Set local machine timezone to GMT +1100 (or likely others)
2. Run `master` unit tests

# Possible solutions
Trying to find a fix I found a couple of options:
#### Using local times for the unit tests
https://github.com/renovateapp/renovate/compare/master...jahredhope:local-times-for-testing

#### Having the worker use UTC when there is no timezone
https://github.com/renovateapp/renovate/compare/master...jahredhope:use-utc-time-as-default

**Comment by rarkins** [comment]
Interesting bug! Thanks for digging into it. I think that the first option (modifying tests) is best as otherwise it would likely count as a backwards incompatible change for people running Renovate themselves and allowing it to default to their local Timezone.  Ie they’d be forced to configure Timezone whereas previously it defaulted to whatever the underlying system has.
