### ISSUE TITLE
Lock file maintenance PRs should not have multiple commits

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1425]
This PR has two Renovate commits and was not edited by anyone else:
https://github.com/mozilla/treeherder/pull/3158#issuecomment-359391376

I'm presuming the issue is that the current "has this PR been edited logic" relies on the count of commits being greater than 1, but the lockfile maintenance logic doesn't replace the initial commit and instead adds later commits when refreshing?

**Comment by edmorley** [comment]
I wonder if Renovate needs to have an understanding of what GitHub user is being used to make the commits after all, and that used to determine if a PR has been edited instead?

The "commits > 1" seems fragile, since if a user decides to pull down the Renovate branch, make changes, then replace the entire commit with their own, presumably Renovate would still overwrite the changes.

**Comment by rarkins** [comment]
> but the lockfile maintenance logic doesn't replace the initial commit and instead adds later commits when refreshing?

Yes, I think it's related to the lock file maintenance. I had forgotten that and think I will "fix" that to make it cleaner for the user to see only one commit.

> I wonder if Renovate needs to have an understanding of what GitHub user is being used to make the commits after all, and that used to determine if a PR has been edited instead?

I wanted to stay away from needing to know "who" the bot is on GitHub, because the tool can be run by anyone from CLI, and so that adds extra complexity to work out the current user, etc. Also sometimes people run the bot with their own token, meaning both the bot's commit(s) as well as ones they make manually show up as the same user. Now in such a case you wouldn't want Renovate to assume "looks like these are all my own commits - I'm free to overwrite them".

> then replace the entire commit with their own

![image](https://user-images.githubusercontent.com/6311784/35218054-91ab5a26-ff6d-11e7-9177-27e4b6c12e7c.png)

But yes you're right. If someone hijacked one of Renovate's branches and force pushed a single commit over the top of Renovate's, then Renovate will be oblivious and take the branch back again the next time it needs to.

**Comment by edmorley** [comment]
> because the tool can be run by anyone from CLI

Ah I not realised this case (I was just thinking the official Renovate app + people with a self-hosted instance).



> But yes you're right. If someone hijacked one of Renovate's branches and force pushed a single commit over the top of Renovate's, then Renovate will be oblivious and take the branch back again the next time it needs to.

This is the workflow I use with pyup.io sometimes. It's not a problem to change to a "add a second commit, and when merging use squash and merge" workflow instead, but hadn't realised the risk until now.

**Comment by edmorley** [comment]
> Yes, I think it's related to the lock file maintenance. I had forgotten that and think I will "fix" that to make it cleaner for the user to see only one commit.

Having only one commit will actually fix another small issue too that I'd forgotten about -- when using "squash and merge" with the lockfile maintenance PRs I've always had to edit the final commit message so it doesn't contain:
```
* Update lock file

* Update lock file
```

**Comment by rarkins** [comment]
I'll think if there's a way to detect "whoami" and use that logic instead, even if I "fix" lock file maintenance to be just one commit always, like other branches.

I'm also not sure why Renovate felt the need to update this particular lock file anyway, if there was already an open branch. I had intended the functionality so that if there was already a lock file maintenance PR existing then Renovate does not even try to refresh it again. Otherwise the result would be Renovate regenerating lockfiles every single run just in case something changed, which is very inefficient. So my approach was: if you care so much about your lock file, merge the PR immediately. Or ideally automerge. Then you can get another refresh if youso wish (e.g. schedule allows it).

**Comment by rarkins** [comment]
Hope you don't mind, I've renamed this to reflect what I consider to be the "root cause". The second issue of "should Renovate assume 1 commit = its own commit?" can be solved separately.

**Comment by edmorley** [comment]
> Hope you don't mind, I've renamed this to reflect what I consider to be the "root cause". The second issue of "should Renovate assume 1 commit = its own commit?" can be solved separately.

Makes sense - thank you!

> I'm also not sure why Renovate felt the need to update this particular lock file anyway, if there was already an open branch.

So I'd noticed this happen in previous weeks - we'd get several updates to the lockfile maintenance PR in the time between when it opens and when I have a chance to merge it. Initially it seemed like a bug, however a nice side-effect is that is means when I do merge the PR it is at least fully up to date. Perhaps the real solution here is to just use automerge for the lockfile maintenance PRs once I'm confident they are doing the right thing.

**Comment by rarkins** [comment]
> Perhaps the real solution here is to just use automerge for the lockfile maintenance PRs once I'm confident they are doing the right thing.

For you, yes I agree - that would be best in the long term. After all:
- we're talking *in range* updates here, satisfying your `package.json`
- it would only automerge if it passes tests, too

So it's pretty much the safest thing you can automerge. But in the meantime I'd like them to stop updating. I suspect it may conflicts that triggered it actually.

**Comment by rarkins** [comment]
Checking the logs for when that second commit was made:
```
"Only 1 commit in PR so rebase is possible"
"Existing PR is open"
"Package not scheduled"
"Branch exists but is not scheduled -- will update if necessary" 
```
Our default functionality is to resolve conflicts or perform automerges even if outside schedule - schedule limits only branch *creation*. e.g. it might take 1-2 hours to test, by which time the schedule is over, but it still makes sense to do the automerge then.
```
"Branch does not need rebasing"
"Using parentBranch: renovate/lock-file-maintenance"
"isBranchStale(renovate/lock-file-maintenance)"
```
... here is the key point .. but logs don't help
```
"Generating yarn.lock for ."
"yarn.lock needs updating"
```

**Comment by rarkins** [comment]
The weird thing about this is that the fix is reverting a one-line commit from 5th December. Existing lock files will not get commits added on top anymore - it was doing it whenever they became "stale". Or at least, it was checking if they should be updated whenever they were stale.
