### ISSUE TITLE
Changelog/release notes need to use github.com

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1471]
Cc @destroyerofbuilds

**Comment by destroyerofbuilds** [comment]
When resolving the GitHub Release Notes end-point, Renovate should generate a GitHub URL that is based on the value of the `repository.url` property in the npm dependency's `package.json` metadata fetched from the npm registry. (This is applies to other language package registries as well)

This way Renovate is independent of where a dependency chooses to keep their authoritative source repository (Whether BitBucket, GitLab, or GitHub)

**Comment by rarkins** [comment]
Yes, agreed. But I’d like to get hardcoded GitHub working first and then expand it

**Comment by destroyerofbuilds** [comment]
So as we discovered, it turns out that `changelog` is [using a GHE token to make requests to `github.com`](https://github.com/dylang/changelog/blob/144d2d40bf9179d81e2c0093016c12a22edef809/lib/datasrc/github.js#L33).

That causes the following error to be thrown - `Unknown Github Repo: git+https://github.com/nuxt/nuxt.js.git. Bad credentials`

**Comment by rarkins** [comment]
Maybe a short term fix is to unset then set `GITHUB_TOKEN`, although a I think unauthorised will exhaust agh rate limits quickly.

**Comment by rarkins** [comment]
Solved with short-term fix in `latest`. `GITHUB_TOKEN` is unset prior to changelog generation if  a custom github endpoint is already in use.
