### ISSUE TITLE
PR opened after unpublish-safe succeeded needed rebasing

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1492]
Hi!

This PR was opened after the 24 hour unpublish check succeeded:
https://github.com/mozilla/treeherder/pull/3201

...however when the PR was opened it already says "This branch has conflicts that must be resolved", since at some point in the 24 hours package.json was updated, but it hasn't been rebased.

I think it perhaps makes sense that the branch wasn't rebased whilst the status check was pending (since it might end up needing to be rebased multiple times), however I think prior to opening the PR, Renovate should rebase it, and then continue to do so when it is open.

**Comment by rarkins** [comment]
@edmorley did Renovate resolve the conflicts after that, without manual intervention?

I think we need a PR to be able to tell if the branch is in conflict or not. i.e. GitHub do not expose that calculation on branch-only. Perhaps the only way to solve it is to detect the combination of `unpublishSafe=true` and `prCreation=not-pending` and actually skip branch creation too until after 24 hours. Although even that can't guarantee it because it could go into conflict after we create branch but before *other* branch checks have completed.

**Comment by edmorley** [comment]
Ah when I filed the issue the PR hadn't been rebased (was 30+ minutes after it was opened), but must have been at the next cycle. I guess maybe Renovate could check if the PR needs rebasing it at the same time as opening (to save the 1 hour delay), but I totally understand if that's not worth the effort, given conflicts don't occur too often.

Failing that, perhaps it would be worth holding off creating the branches for new releases until the last few hours of the 24 hours unpublish safe window?
