### ISSUE TITLE
Subsequent `npm install` results in `package-lock.json` changes

### ISSUE THREAD

**Issue by ctaepper** [renovateapp/renovate#1495]
hi @rarkins, first of all, thanks for merging and releasing our #1443 branch. it is in production use now and everything works as expected.

almost :)

I noticed something that I don't think is related to the lerna setup, i'm not sure though

1. devdependency `@types/node` needs to be renovated (in our case its defined in a lerna root packages.json
2. renovate does its job as expected and updates the `package.json` and `package-lock.json` with the updated version
3. I accept the PR (or gets automerged) and update my local branch.
4. i execute `npm install` in order to update my local node_modules
5. *BUT* installing leeds to a change in `package-lock.json`: the change is within some other dependency which has also a dependency to `@types/node`. the version of this subdependency gets aligned to the renovated version

The expected result of `npm install` should be *no* change in any package file. Can this be a bug in npm's `package-lock-only` flag? I can try to get a example repo up, but I'm not sure if this as easy as last time

**Comment by rarkins** [comment]
So, the way Renovate does it is this:

1. Copies the original `package.json` and `package-lock.json` files
2. Manually patches the `package.json` for the new version(s) necessary
3. Runs `npm install --package-lock-only`

You need the "old" `package-lock.json` there because otherwise it would not only take a long time, but it would refresh *all* locked dependencies. e.g. you might attempt to update package `a` but a failed transitive dependency `c` of dependency `b` breaks things, totally unrelated to `a`.

> The expected result of `npm install` should be no change in any package file

I agree, but I think `npm` is maybe "not there yet". Check out https://github.com/npm/npm/issues/18286

It sounds like `npm install` has done some type of "optimisation" beyond what is preset in the lock file. 

> Can this be a bug in npm's `package-lock-only` flag?

More like a problem with `npm install` not following the lock file. I mean, if `npm install` followed *valid* lockfiles then you wouldn't have a problem. Of course the lock files themselves should ideally be "optimised" perfectly but that wouldn't be as much of a problem if install followed the lock file regardless.

Here's one way to test if you had a time machine or some other way to do this:

1. Check out the Renovate branch and run `npm install`. Verify you see a diff in `package-lock.json`
2. Rename then close/delete the PR
3. Recreate the PR
4. Verify the diff again (i.e. repeatable)
5. Rename then close/delete the PR again
6. Patch Renovate to remove the `--package-lock-only` flag
7. Recreate the PR
8. Run `npm install` again from the branch and see if there's no diff this time

**Comment by rarkins** [comment]
I've clarified with one of the `npm` CLI developers that this will be addressed via an `npm ci` command soon. This command is essentially "install node modules from the lock file" and also will have the benefit of being much faster than `npm install`. You can test it out in the meantime by running `npx npmc ci` as a substitute for `npm install`. I believe `npmc` means the "canary" build of `npm` and the `npx` prefix is just to save yourself the hassle of installing it globally and keeping it updated.

**Comment by rarkins** [comment]
I'm labeling this as a "blocked" "fix" because it's undesirable yet I'm not sure there's anything I can do about it until `npm` does something.

**Comment by fenduru** [comment]
Is this also the expected behavior for yarn lockfiles? Renovate did not update my transitive dependencies in yarn.lock as part of its onboarding PR/subsequent PRs.

**Comment by rarkins** [comment]
@fenduru please raise a separate issue describing exactly what you’re seeing. Answers for yarn and npm will definitely be different.

**Comment by rarkins** [comment]
@ctaepper FYI another user found that `npm` has a bug with `--package-lock-only`: https://github.com/npm/npm/issues/19852

Basically, you get an incorrect `package-lock.json` from `npm install --package-lock-only` sometimes if an existing `package-lock-json` exists. i.e. it's causing some incorrect caching somehow.

For now to work around that I have stopped writing the `package-lock.json` files prior to running `npm install`, however I think I might switch to writing it but running a full `npm install` instead.
