### ISSUE TITLE
Github Enterprise App Support

### ISSUE THREAD

**Issue by mastermatt** [renovateapp/renovate#1497]
Renovate is not listed as compatible with installing on Github Enterprise. 
https://github.com/works-with?utf8=%E2%9C%93&query=renovate&enterprise_compatible=on

I'm not sure if this is just an issue with how it's listed with Github or if work needs to be done.

**Comment by rarkins** [comment]
Yes, the Renovate *App* (https://github.com/apps/renovate) is not showing up as compatible, although I have no idea what it takes to get that tick - I checked again and there's no options I need to tick in the admin panel so I may need to contact GH. They can be quite "secretive" at times, and app support for GHE is still considered beta.

FYI:
- The Renovate CLI (i.e. `npm install -g renovate`) is and has been compatible with GHE almost since it was released a year ago.
- I published a small "wrapper" around `renovate` this week (https://github.com/renovateapp/github-app-cli) that @destroyerofbuilds is testing out. I will publish it to npmjs once it's been tested out and confirmed working - feel free to `git clone` it and try it if you wish to use "app mode" instead of a personal access token

**Comment by destroyerofbuilds** [comment]
@rarkins please feel free to pass along anything to me if there's some way I can reach out to GHE support regarding the Enterprise listing.

@mastermatt as @rarkins has noted, `renovate`, the CLI, is quite compatible with GitHub Enterprise (We have been using it there for about 6 months), though there have been a few issues with some features of Renovate (Such as fetching changelogs, etc.) which @rarkins has been kind enough to work through as they come up.

@mastermatt also as noted by @rarkins, `github-app-cli` wraps Renovate, and integrates it with GitHub's App API to fetch repositories. It works, with the exception of one major bug: It makes requests to `github.com`. I just needed to replace those URLs with `process.env.RENOVATE_ENDPOINT` to re-use the environment variables from `renovate` for setting the GHE API endpoint.

I plan on submitting a patch for that today (I've been a little backlogged with GHE App workflow issues).

**Comment by mastermatt** [comment]
I've been using the CLI successfully for a couple of months, but I'm trying to get buy in from other teams in our org and being able to install it in our GHE would go along way.

Thanks for the info, keep us updated if your comms with support get anywhere.

**Comment by destroyerofbuilds** [comment]
So it looks like @rarkins went ahead and fixed the endpoint issue in `github-app-cli`.

@mastermatt in our specific situation we created a dedicated service account, and setup `renovate` to autodiscover all repositories on which the service account was added with _Write_ access.

It has worked quite well in lowering the barrier for other teams to on-board with Renovate.

**Comment by destroyerofbuilds** [comment]
Would it be useful to migrate this discussion over to https://github.com/renovateapp/github-app-cli where the GitHub App implementation exists?

**Comment by rarkins** [comment]
Migrated to https://github.com/renovateapp/github-app-cli/issues/10
