### ISSUE TITLE
Add option to keep the renovate process alive listening for incoming webhooks

### ISSUE THREAD

**Issue by StephanBijzitter** [renovateapp/renovate#1499]
Self-hosting is pretty awesome, but with a very active repository where we love automation, a timed schedule would leave pull requests longer open than needed before they're automatically merged.

Currently (unless I skipped over it in the documentation), instant action would require me to configure a github webhook and let our server listen to incoming events (when something gets merged to master), to then re-run renovate. It would be really nice if this could become part of renovate itself.

For example the command would look like `yarn renovate --listen={port:443}`. This would fire up a server that listens on the specified port and runs renovate whenever there's a push to the base branch or when a branch completes status checks and/or has been reviewed.

**Comment by rarkins** [comment]
This is how the hosted GitHub app works currently. If you are hosting on github.com rather than GHE then I suggest you switch to app mode to get this benefit. Handling the concurrency was quite a challenge to get right, i.e. not getting swamped, not running too many at once, not running twice on the same repo, etc. Right now it's implemented using several "serverless" features on AWS so it's not a matter of simply open sourcing it, but I plan to rewrite the web handlers and queueing logic into an "enterprise" release soon that will probably use multiple Docker containers.

**Comment by rarkins** [comment]
Webhook listening capability is now part of "Renovate Pro Edition", which was released today. See https://renovatebot.com/pro for details. 

Cc @StephanBijzitter @Aghassi 

GitLab support will be added to that project and tracked in https://github.com/renovatebot/pro/issues/3
