### ISSUE TITLE
[regression] unexpected automerging

### ISSUE THREAD

**Issue by ikatyang** [renovateapp/renovate#1584]
`automerge: "patch"` but Renovate automerged `minor` upgrades, I guess there's something wrong in c6be31543df1ef1edfd41daf5bb600ebdb192ad8.

config: https://github.com/ikatyang/prettier-config-ikatyang/blob/master/renovate.json
pr: https://github.com/ikatyang/prettier-config-ikatyang/pull/59

config: https://github.com/ikatyang/tslint-config-ikatyang/blob/master/renovate.json
pr: https://github.com/ikatyang/tslint-config-ikatyang/pull/104
pr: https://github.com/ikatyang/tslint-config-ikatyang/pull/65

**Comment by rarkins** [comment]
Thanks for alerting me, I'll roll back the version in the app now and then re-check the logic.

**Comment by rarkins** [comment]
@ikatyang I checked the logs and it looks like you were the only one affected. It happened due to:
- "old" setting of `"automerge": "minor"` in preset
- "old" setting of `"automerge": "patch" in config
- auto grouping of `@types/prettier`

Anyway I'll leave it with the previous migration for now. I'll soon add a feature to Renovate that will raise a PR for config migration from deprecated fields to current ones.
