### ISSUE TITLE
Provide official docker image on DockerHub for self-hosted renovate

### ISSUE THREAD

**Issue by felixfbecker** [renovateapp/renovate#1609]
It would be awesome if there was an official, always up-to-date, guaranteed-to-work , properly tagged Docker image on Docker hub for self-hosted renovate that could just be dropped into an infrastructure.

**Comment by rarkins** [comment]
@felixfbecker thanks for the suggestion. There's been a PR in place for quite some time that I kind of sat on: https://github.com/renovateapp/renovate/pull/734

Perhaps you could validate my current thinking if this is the right way to go?

1. It should use Docker Hub autobuild directly from the renovateapp/renovate github repository to ensure it's the same as you get via npm.
2. It should build based on tags, i.e. after semantic-release tags a new release, that should trigger Docker Hub to build the same
3. There needs to be a post-upgrade hook for Docker Hub that tags it on the server side with major and minor tags. e.g. if I publish `11.30.1` then I want that same image also tagged as `11` and `11.30` for those who want to not have so much churn in their versions

And finally, do you think point (3) is a showstopper or should I go ahead with 1+2 and implement 3 later? It was (3) that was holding me up, but maybe done is better than perfect in this case.

**Comment by felixfbecker** [comment]
Great to see you are using semantic-release 👍 Automatic releases would be the benefit of having this official.

I wrote https://github.com/felixfbecker/semantic-release-docker to have more control over the build process of the image (I use it e.g. for https://github.com/felixfbecker/php-language-server). I could very easily add support for tagging the minor and major versions, I think that's a great feature. WDYT?

**Comment by rarkins** [comment]
Ideally I'd like to avoid yet another set of credentials sitting on CI. I'm already trying to work out how I can move or refactor semantic-release as it is so that Travis CI doesn't need the tokens, as I don't like that they are another attack vector on a project/person. This is the reason I am holding back adding other collaborators with write access in fact.

For now I would lean towards the Docker Hub autobuild solution, because it could be implemented without further dependencies or setup, so long as (3) is possible using this approach: https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands (hooks/post_push)

Perhaps I'll do this: Now that there is build-up demand, I will prioritise the Docker Hub autobuild approach myself (unless you would like to help update/fix the Dockerfile we tried previously). If I think hooks/post_push is a dead end for getting the tagging how I like it, we can discuss again about delegating all pubishing to semantic-release-docker.

**Comment by sylvaindumont** [comment]
I've built [docker-renovate](https://github.com/sylvaindumont/docker-renovate) to fix the missing parts of the current docker pr, it adds a cron, is updated via renovate, autobuild `latest` via docker hub automated build and push a tag for each version via travis.

It doesn't create major/minor tags and force to keep docker credentials in travis.

It could be a solution until someone finds time to build a clean solution with docker hub autobuild.

**Comment by felixfbecker** [comment]
@rarkins I see your concerns - ideally Travis would have a feature like VSTS that allows _substitution_ of secrets in commands as command flags instead of env vars so they don't get leaked into all child processes. Lockfiles mitigate the issue a bit if you trust your dependencies. Overall I still think it is worth the automation, I would rather trust a machine with publishing, and if it needs keys for that, I hand them over. I would like to point out that adding another pair of credentials in addition to the github tokens doesn't really make a difference because if an attacker got control over them it can change the source code, publish releases and already do the maximum damage. Having the image be built by Docker wouldn't make a difference at that point.

**Comment by rarkins** [comment]
@felixfbecker I completely agree with you that the risk would be less, but I haven't decided yet if I keep semantic-release as part of CI, so it would be one more thing to roll back.

For most projects the tradeoffs are probably worth it, but I'm quite paranoid for this project now considering how many people and companies depend on Renovate and the position of trust it's in.

**Comment by rarkins** [comment]
@sylvaindumont thanks for the info! Could you explain what the need was for the extra packages in your Dockerfile? In case I'm missing something

```
RUN apk add --quiet --no-cache --virtual .gyp \
  python \
  build-base \
  git \
  && yarn \
  && yarn cache clean \
  && apk --quiet del .gyp
```

The Dockerfile I have in #1619 seems to build and run fine without .gyp, python, build-base or git being added first.

**Comment by sylvaindumont** [comment]
@rarkins  When I built the image for the first time (11.25.20), bunyan->dtrace-provider needed python to build, so I added these build dependencies, they are removed once yarn finished and have no impact on image size, but they slow image build. .gyp isn't a dependency, it's [just a name to group build deps](https://stackoverflow.com/questions/46221063/what-is-build-deps-for-apk-add-virtual-command#answer-46222036).

Others versions don't need these dependencies but it could be useful to add them in the first stage of your build to avoid breaking docker build the next time a deep dependency require them.

**Comment by rarkins** [comment]
Thanks for the info. I’m a little hesitant to add deps “just in case” though if right now it appears to be working.

**Comment by rarkins** [comment]
I think this is now working, including some advanced tagging.

Renovate can now be run like this:
```
$ docker run -e GITHUB_TOKEN renovate/renovate user/repo
$ docker run -e GITHUB_TOKEN renovate/renovate:11 user/repo
```

The `latest` tag is what's built from `master`. But because we use `semantic-release`, there should usually be a versioned tag coming soon after. A post-hook script also ensures `x`, `x.y`, `x.y.z` tags are pushed too:

![image](https://user-images.githubusercontent.com/6311784/37213535-a012f312-23b2-11e8-84c2-bcceb57ea64c.png)
