### ISSUE TITLE
rebaseStalePrs=false is not working

### ISSUE THREAD

**Issue by Flewd** [renovateapp/renovate#1623]
Hello! 

In this documentation: https://renovateapp.com/docs/configuration-reference/configuration-options

It mentions the field "rebaseStalePrs" which should default to false. our repo's renovate PRs were still auto rebasing even after explicitly setting rebaseStalePrs to false in the renovate.json file.

This was causing issues in our CI environment and giving our Jenkins machine some unneeded stress. for the time being I am sidestepping the issue by setting the base branch for the renovate PRs to not master, until we are reviewing and merging that PR.

Let me know if there is any other information I can provide to help with this!

**Comment by rarkins** [comment]
This is likely caused by Renovate detecting this setting is enabled on you repo:
![image](https://user-images.githubusercontent.com/6311784/37191555-b891cb04-2360-11e8-87cd-8b6874a97a79.png)

I'll refactor the feature a little so that the default for `rebaseStalePrs` is `null`, and if you manually set it to `false` then we'll skip rebasing even if you have configured your repo to enforce it.

**Comment by rarkins** [comment]
@Flewd it should now be fixed in the app if you wish to retry. I changed default from false to null so we can detect if you have manually forced it to false

**Comment by Flewd** [comment]
Awesome! Just confirmed, the renovate branches are no longer autoRebasing, thank you for the change!
