### ISSUE TITLE
Lock file maintenance PR failed with stderr 'undefined'

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1649]
#### This is a:

* [X] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [X] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Hi!

I just enabled yarn lockfile refreshing on the mozilla-neutrino/neutrino-dev repository - and the first lockfile update PR (mozilla-neutrino/neutrino-dev/pull/743) failed with:

> Lock file problem
> 
> Renovate failed when attempting to generate a lock file.
> ...
>
> The output from `stderr` is included below:
> 
> ##### packages/react-components/yarn.lock
> 
> ```
> undefined
> ```

Is this perhaps because this repository uses yarn workspaces?
https://github.com/mozilla-neutrino/neutrino-dev/blob/f598144da0db801794ca7c4648fdcfe52a799d1c/package.json#L14-L16

Many thanks :-)

**Comment by edmorley** [comment]
Ah so it turned out the issue was a stray `yarn.lock` in one of the packages in the workspace (when we only meant to have the repo root `yarn.lock`).

I'll leave it up to you to decide whether the `undefined` is a bug (if there was no stderr, perhaps it should say "No output" or similar?) :-)

**Comment by rarkins** [comment]
@edmorley if you can work out a simple repo/example to reproduce it, I can take a look. Otherwise it's frankly going to remain low in priorities if I need to be able to reverse engineer a solution from the logs. It might be as simple though as the stray lockfile wasn't found after workspaces was run, although adding "lock file not found" isn't that much more of a help over `undefined` :)

**Comment by edmorley** [comment]
I'm happy to ignore this for now :-)
