### ISSUE TITLE
Can pinDependencies PRs be automerged?

### ISSUE THREAD

**Issue by bahmutov** [renovateapp/renovate#1663]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

When Renovate notices ranges, it creates a PR to pin dependencies. Can these PRs be automerged? So far it seems to require manual merge.

**Comment by rarkins** [comment]
Pinning should follow automerge rules, i.e. disabled by default but automerges if you enable the setting in config. I originally had Pin Dependencies automerge by default but users did not appreciate that behaviour so that didn't last for long.

Remember too that automerging can currently take up to an hour after status checks go green.

Do you have a PR not automerging that I can look at?

**Comment by bahmutov** [comment]
Great, it did in fact just auto merged this PR https://github.com/bahmutov/vue-vuex-todomvc/pull/12

**Comment by bahmutov** [comment]
Ha I just noticed that I am working both with `renovate[bot]`  and `renovate-bot`
<img width="340" alt="screen shot 2018-03-14 at 2 54 02 pm" src="https://user-images.githubusercontent.com/2212006/37424722-92fa92dc-2797-11e8-86ae-82932dda4829.png">

**Comment by rarkins** [comment]
Yes, GitHub "[bot]" accounts - i.e. the app's identity - aren't full users and cannot do things. For example they don't have a real email address, and as a result they can't sign commits. As a result the Renovate bot is configured to author and sign as the @renovate-bot user so that these things can be done.

FYI: Renovate always keeps itself to 1 commit per branch (unless you yourself add more on top, e.g. to fix a break). So if you have a regular Renovate PR then the best way to merge manually is with Rebase merge so that you get a single, signed commit on top of master.
