### ISSUE TITLE
separate GITHUB_TOKEN for public and enterprise

### ISSUE THREAD

**Issue by dylang** [renovateapp/renovate#1685]
#### This is a:

* [ ] Bug report (non-security related)
* [X] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [X] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

We use Github Enterprise, so our `GITHUB_TOKEN` is for our enterprise server. This works great, except with the version of Renovate we are currently using (`11.21.20`), we run out of API calls to the public Github.com every hour, and with the newer version of Renovate (`11.37.9`), it gets `Bad credentials (401)` errors, we think because the `GITHUB_TOKEN` is for our enterprise server only.

The feature request is to have two tokens, one for enterprise, and one for the public github.com.

Thanks!

**Comment by rarkins** [comment]
@dylang please try setting `GITHUB_COM_TOKEN` to be a token for the public github.com and leave `GITHUB_TOKEN` as your enterprise token.

FYI it was added here: https://github.com/renovateapp/renovate/commit/9cd579ddb345ddcd490d545bd67bbcfa929f667a

Please confirm and close if it works

**Comment by dylang** [comment]
Ha, great, will try!

**Comment by djmadeira** [comment]
Took at look at this, still doesn't work for us. It's still making every request to our GHE instead of public GitHub, including requests like `/api/v3/repos/renovateapp/renovate/releases?per_page=100`.

I think the reason for this is that [gh-got reads from the GITHUB_ENDPOINT environment variable](https://github.com/sindresorhus/gh-got/blob/master/index.js#L15). I see that you are [deleting it from process.env](https://github.com/renovateapp/renovate/blob/23d0290384b53fcb66a63cfd148f3fd1dd6c0a01/lib/workers/pr/index.js#L112), and I can see `Removing GHE token before calling changelog` in our logs, so in theory it should be unset, but it's not. Not sure why yet.

**Comment by rarkins** [comment]
@destroyerofbuilds is/was this working for you?

**Comment by djmadeira** [comment]
@rarkins I'm curious how this code is designed to work. The code seems to only read this value from process.env, when it's possible to specify the token both as an argument and in renovate.js. Is this a gap, or an intentional design choice?

**Comment by rarkins** [comment]
It’s an inelegant solution right now. It is meant to work because the library `changelog` also recognises `GITHUB_TOKEN` so the idea is we temporarily swap in the public one and then swap it back again. 

BTW if you configure `token` in settings then we *export* it to env at the start of running, so that’s why it is meant to work even if you haven’t exported GITHUB_TOKEN to begin with

**Comment by rarkins** [comment]
Repeating here the logic in case it helps either of us work out what's going wrong:

##### What are we trying to do?

Make sure that changelog/release lookups query the public github server and not the configured enterprise server

##### Why would that happen anyway?

1. Currently, we export `GITHUB_TOKEN` to env - even if it's configured via Renovate config options - so that the `gh-got` library reads it on every request. The external `changelog` library also reads this in, so if it's set to an Enterprise token then it will be incorrect for github.com

2. Our own logic for looking up releases also uses `gh-got`, and hence it would otherwise use the GHE token and endpoint for lookups if we don't delete them from env first.

##### How is it done?

If a github endpoint is set - this is a sign of GHE in use - then we temporarily save and delete the endpoint, and we save and then set `GITHUB_TOKEN` to take the value of `GITHUB_COM_TOKEN`. Source: https://github.com/renovateapp/renovate/blob/23d0290384b53fcb66a63cfd148f3fd1dd6c0a01/lib/workers/pr/index.js#L109-L115

After changelog/release notes lookups are done, we swap them back. Source: https://github.com/renovateapp/renovate/blob/23d0290384b53fcb66a63cfd148f3fd1dd6c0a01/lib/workers/pr/index.js#L174-L178

**Comment by rarkins** [comment]
@djmadeira I've released a fix to hardcode api.github.com for the releases lookup but that cannot be the final "fix" because GITHUB_ENDPOINT should be deleted from `env` already. i.e. there's some other logic problem that this may just bandaid over. Please describe in more detail how you are configuring and what you are seeing and maybe it will become more obvious.

**Comment by rarkins** [comment]
Just to be clear:

- GITHUB_TOKEN is for your GHE and needs read/write access. It maybe configured via "token" instead of env
- GITHUB_COM_TOKEN is for the public github.com server and needs only read-only access. It's just used for changelog lookups and can only be specified via env for now

**Comment by destroyerofbuilds** [comment]
> @destroyerofbuilds is/was this working for you?

This has been working in our GHE installation for a while now.

We set the following:

* `GITHUB_COM_TOKEN`
* `RENOVATE_ENDPOINT`
* `RENOVATE_PLATFORM`
* `RENOVATE_TOKEN`

**Comment by djmadeira** [comment]
Confirmed that using `GITHUB_COM_TOKEN`, `RENOVATE_ENDPOINT`, and `RENOVATE_TOKEN` fixes the issue for us.
