### ISSUE TITLE
Closing pull requests do not ignore grouped package upgrades

### ISSUE THREAD

**Issue by wopian** [renovateapp/renovate#1716]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

If a PR is closed unmerged, Renovate comments that it will ignore the upgrade and will wait for future releases. This does not happen with package groups - where the PR is immediately recreated upon closing.

While removing the grouping is temporarily viable, it'll just cause more issues later on as they will all be broken branches as they all depend on `webpack`'s version being `4.x`.

This is slowing Appveyor CI to a crawl with 2-12 extra builds triggered per master commit against these branches

https://github.com/wopian/kitsu-season-trends/pull/64
https://github.com/wopian/kitsu-season-trends/pull/75
https://github.com/wopian/kitsu-season-trends/pull/76
https://github.com/wopian/kitsu-season-trends/pull/77
https://github.com/wopian/hibari/pull/470
https://github.com/wopian/hibari/pull/489

<details><summary>Config used</summary>

```json
{
  "renovate": {
    "extends": [
      ":npm",
      ":preserveSemverRanges",
      ":combinePatchMinorReleases",
      ":renovatePrefix",
      ":semanticCommits",
      ":semanticCommitTypeAll(chore)",
      ":rebaseStalePrs",
      ":unpublishSafe",
      ":prNotPending",
      ":automergeDisabled",
      ":maintainLockFilesMonthly",
      ":ignoreUnstable",
      ":updateNotScheduled",
      ":label(dependencies)",
      ":timezone(Europe/London)",
      ":assignee(wopian)",
      "group:babelMonorepo",
      "group:jestMonorepo",
      "group:reactMonorepo",
      "group:storybookMonorepo"
    ],
    "prTitle": "update {{depName}} to {{newVersion}}",
    "commitMessage": "update {{depName}} to {{newVersion}}",
    "packageRules": [
      {
        "packagePatterns": [
          "^webpack"
        ],
        "groupName": "webpack"
      }
    ]
  }
}
```
</details>

**Comment by rarkins** [comment]
Renovate uses the combination of group name + PR title as the "primary key" to know if an upgrade exists, or used to exist. With groups, it's not possible to block them because it would mean blocking the "webpack" group *forever*. 

There are a few compromises, maybe you can pick one

- You can add `"recreateClosed": false` to your package rule, this should mean that the PR doesn't come back (ever). Find and rename that PR one day when you're ready to actually do the upgrade and this will trigger a new/current PR to be created

- Set `"enabled": false` in your package rule so that it's a bit clearer as to why it's not being raised. Remove that setting later when you're ready t upgrade

> This is slowing Appveyor CI to a crawl with 2-12 extra builds triggered per master commit against these branches

That's mostly because you added the preset `":rebaseStalePrs"`. You can "undo" that for this group so that it only gets updated when it *needs* to be updated (conflict with `master`, or a dependency is updated). Add `"rebaseStalePrs": false` to the package rule.

In future, please raise questions like this in https://github.com/renovateapp/config-help unless you're certain it's a bug. They can always be moved/added here afterwards if confirmed.
