### ISSUE TITLE
Whitelist private dependencies

### ISSUE THREAD

**Issue by marcenacp** [renovateapp/renovate#1721]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

I have two private Github dependencies for which I don't want to commit any authentication token. When posting an update PR, Renovate fails to generate a `yarn.lock`, because it cannot fetch these two repositories.

Would it be possible to whitelist those dependencies, so Renovate can work for all other dependencies?

**Comment by rarkins** [comment]
Unfortunately it's not really a Renovate problem - it's up to npm/yarn. If the `package.json` changes - for any reason - then the lock file needs to be updated. And if *any* of the dependencies listed in the `package.json` cannot be found, then yarn/npm will throw an error and fail to update the lock file. I'm not aware of any way to tell npm or yarn "just ignore dependencies x and y and leave the lock file as it is for them so that I can update z only".

Here's the second part of the problem for *GitHub* dependencies - the only way to authenticate them is via git+ssh. So even if you were to add Renovate to the GitHub repository that is being depended upon, our *API* authentication token won't help us because npm and yarn defer authentication to git+ssh. The only way it works is if the SSH key being used for that git fetch belongs to a GitHub account that is a collaborator.

By the way, I noticed a new account on the app yesterday with the problem you describe (a GitHub org that starts with "the") and have a solution prepared. Is that you?

**Comment by rarkins** [comment]
@marcenacp actually I'm going to play around with this, in case the yarn behaviour is different to what I previously observed or remember. If you can give some specifics about your use case, that would be useful. e.g. exactly how the github dependency is specified in the `package.json`

**Comment by rarkins** [comment]
Interestingly, it seems that `npm` can handle a "missing" dependency when updating lock files but `yarn` cannot. Yarn insists to resolve all `.tgz` files in `yarn.lock` even if it's just updating/upgrading one of the dependencies.

**Comment by rarkins** [comment]
This should work now. The only thing you won't be able to do is "lock file maintenance" because that involves updating the entire lock file, which would naturally fail if some dependencies are not able to be found.
