### ISSUE TITLE
Renovate auto closes a PR/MR

### ISSUE THREAD

**Issue by sarunint** [renovateapp/renovate#1762]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [x] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Please take a look at these screenshots:

![image](https://user-images.githubusercontent.com/3850197/38165412-025cebd6-353d-11e8-935b-125beebdd60c.png)

![image](https://user-images.githubusercontent.com/3850197/38165418-18833eec-353d-11e8-9a06-5db6892ddfa8.png)

I'm not sure why Renovate auto closes this issue. I haven't push any commits to the repo and no merge requests were merge.

**Comment by rarkins** [comment]
Which version are you running?

**Comment by rarkins** [comment]
For now it looks like a duplicate or similar to #1657

**Comment by sarunint** [comment]
Duplicate of #1657 

Thanks!

**Comment by sarunint** [comment]
@rarkins sorry for an off-topic here.

But how do I keep renovate up to date, since there are many releases a day.

**Comment by rarkins** [comment]
How do you install it today? e.g. `git clone` or `npm install -g`?

**Comment by sarunint** [comment]
I `git fetch` them and push to heroku.

**Comment by rarkins** [comment]
The best way would be if you actually create your own repo that “wraps” this one as a dependency so that you can receive and view PRs every time Renovate updates. And reply to Heroku automatically when that wrapper repo commits to master. Ie renovate your renovate Heroku repo. I made an example of that in https://github.com/renovateapp/renovate-heroku you could try
