### ISSUE TITLE
Renovate upgrades Docker image digests in docker-compose.yml and .circleci/config.yml even when docker support is disabled

### ISSUE THREAD

**Issue by openjck** [renovateapp/renovate#1778]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

We have disabled Docker support on the following repos, but Renovate is opening pull requests to pin Docker image digests regardless. The Renovate docs state that [.circleci/config.yml](https://renovateapp.com/docs/configuration-reference/configuration-options#circleci) and [docker-compose.yml](https://renovateapp.com/docs/configuration-reference/configuration-options#docker-compose) support should be disabled whenever Docker is disabled.

* https://github.com/mozilla/distribution-viewer/pull/374 (using [this config file](https://github.com/mozilla/distribution-viewer/blob/a137f5c0cee5ef09f611d0fdec890d36295c792d/renovate.json))
* https://github.com/mozilla/experiments-viewer/pull/388 (using [this config file](https://github.com/mozilla/experiments-viewer/blob/272924ef6ed92ceb791c18333b992ca6f54349f3/renovate.json))
* https://github.com/mozilla/firefox-test-tube/pull/130 (using [this config file](https://github.com/mozilla/firefox-test-tube/blob/af0bbb7fdf65d9d7284603caf3c14769e474502d/renovate.json))

**Comment by openjck** [comment]
Heh, it keeps re-opening them, too.

**Comment by rarkins** [comment]
@openjck sorry for the inconvenience - I have pushed a commit to fix this and those three repositories have been updated already.

FYI, these are all considered their own "manager" so have their own setting. e.g. `"circleci": { "enabled": false }}` would have worked already. What I've done now is check whether a manager's "parentManager" is disabled too, so you don't need to add any extra config. Docker Compose and CircleCI both have "docker" as their parent manager, while nvm and travis have "node" as theirs.

Also, I have recently added a new configuration option `enabledManagers` where you can explicitly *whitelist* managers you want. e.g. `"enabledManagers": ["npm", "node"]`

Finally: Digest pinning PRs are intended to be reopened if necessary, as noted in the PRs themselves - so that behaviour is not unintended or a bug. i.e. such PRs need to either be merged, or the config updated so that they are disabled.

**Comment by openjck** [comment]
That all makes sense. Thank you for the very quick fix, @rarkins!
