### ISSUE TITLE
Deleting merged branch before renovate actives causes branch to be stuck

### ISSUE THREAD

**Issue by OmgImAlexis** [renovateapp/renovate#1865]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
If the person merging the PR happens to hit delete before the webhook starts Renovate it gets stuck. The only way I found to get it working again is to restore the branch and let Renovate kick in again.

Ref: https://github.com/OmgImAlexis/upcast/pull/9

![screen shot 2018-04-26 at 2 11 04 pm](https://user-images.githubusercontent.com/6525926/39286242-f3cc8eae-495b-11e8-8e55-9d42da22cdfe.png)

**Comment by rarkins** [comment]
Can you explain more what you mean by "gets stuck"? i.e. you were expecting Renovate to do something afterwards, and it did not?

**Comment by OmgImAlexis** [comment]
I was expecting renovate to notice that even though I deleted the branch it still succeeded with merging since the merge itself had no issues.

**Comment by rarkins** [comment]
I think that should still have been the case - Renovate should be able to handle you deleting the branch or it deleting it for you if you leave it open. What type of confirmation or action were you expecting to see that didn't occur? e.g. new PRs created, existing PRs rebased, etc?

**Comment by OmgImAlexis** [comment]
No new PRs were open until after Renovate deleted the branch itself.

**Comment by rarkins** [comment]
It looks like it was just a confusing coincidence, I'll try to explain.

First of all, be aware that the Renovate App:
- Queues up every repository once per hour, with lowest priority setting
- Reacts to any relevant webhooks (e.g. PR merged, config updated, etc) at other times with higher priority so the repository gets jumped to the start of the queue

The result is that the app is mostly "responsive" to changes you make, while also running hourly just in case anything was not caught by a webhook.

When I check the logs for the job that ran immediately after you closed/deleted the PR, I see `PR hourly limit remaining: 0`. This is because the default behaviour - as mentioned in the onboarding PR - is to raise maximum two new PRs per calendar hour. This means that no new PR was raised after the webhook.

About 18 minutes later, the repo was queued up for hourly batch processing and was still waiting in the queue about 40 minutes later when you restored the branch, which triggered a webhook and and on-demand run.

To you, it looked like you needed to restore the branch to get Renovate unstuck. In fact, Renovate had just been blocked due to the hourly limit and would have soon processed your repository anyway.

**Comment by rarkins** [comment]
FYI, you can view the debug logs for any of your repositories by logging in at https://renovatebot.com/dashboard and then browsing to the relevant repository.

I'm open to ideas of how to improve this for others in future though, e.g.
- raise the default hourly limit to 3 or 4, so it's less likely to be noticed?
- alert the user somehow that rate limiting has been reached? I'm not sure how to do that without it being unnecessary noise for the repository

**Comment by OmgImAlexis** [comment]
That doesn't work for me. I only see up to `OmgImAlexis/cors-gate` I believe I may have too many repos and when I try and visit the page `https://renovatebot.com/dashboard#/repos/OmgImAlexis/upcast` it doesn't load the route so I'm not sure what to do now.

Maybe allow the onboarding PRs to have a higher limit or add a burst limit for multiple "actions" such as when Renovate needs to open multiple PRs for onboarding, etc.

Users knowing about the dashboard would be good in the first place. I didn't even realise it existed until you just mentioned it so maybe getting that to users when they onboard would be a good idea for cases like this.

**Comment by rarkins** [comment]
The dashboard is brand new and kind of in alpha/beta stage, so that's why I'm not promoting it heavily yet.

Re "too many repos", I've added a param that should increase the number of retrieved repos from 30 to 100 - can you confirm if you log back in that you see more now? We'll need further code updates to fully implement pagination.

I'll raise an issue internally with the developer who built the dashboard to work out why the route didn't work for you.

Re the PR limit, it's there precisely *because* of onboarding, actually. Users didn't want their CI systems to be swamped with too many PRs once they merged the onboarding PR. This setting can be changed or even disabled using the `prHourlyLimit` configuration option.
