### ISSUE TITLE
Renovate doesn't automerge all pending PRs

### ISSUE THREAD

**Issue by hi-larry** [renovateapp/renovate#1939]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Renovate opened 8 PRs that could all be auto-merged, but only one PR is auto-merged at a time. Re-run the command again, it auto-merged only one PR. Debug log says there are no PRs found (no Renovate branches found) while there are still 6 PRs opened. What could be the cause?

```
DEBUG: Retrieved branchList (repository=LYNX/TestDep_F)
       "branchList": [
         "gh-pages",
         "master",
         "renovate/chai-4.x",
         "renovate/eslint-3.x",
         "renovate/eslint-4.x",
         "renovate/istanbul-0.x",
         "renovate/jsdoc-3.x",
         "renovate/mocha-2.x",
         "renovate/mocha-5.x",
         "renovate/renovate-12.x"
       ]
DEBUG: branchExists(renovate/chai-4.x)=true (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/eslint-3.x)=true (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/istanbul-0.x)=true (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/jsdoc-3.x)=true (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/mocha-2.x)=true (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/renovate-12.x)=true (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/rimraf-2.x)=false (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/eslint-4.x)=true (repository=LYNX/TestDep_F)
DEBUG: branchExists(renovate/mocha-5.x)=true (repository=LYNX/TestDep_F)
DEBUG: 8 PRs are currently open (repository=LYNX/TestDep_F)
[...]
DEBUG: branchPrefix (repository=LYNX/TestDep_F)
       "branchPrefix": "renovate/"
DEBUG: getPrList() (repository=LYNX/TestDep_F)
DEBUG: Found 0 Renovate PRs (repository=LYNX/TestDep_F)
       "renovatePrs": []
DEBUG: Removing any stale branches (repository=LYNX/TestDep_F)
DEBUG: config.repoIsOnboarded=true (repository=LYNX/TestDep_F)
DEBUG: branchList and deletedBranches (repository=LYNX/TestDep_F)
       "branchList": [
         "renovate/renovate-12.x",
         "renovate/jsdoc-3.x",
         "renovate/rimraf-2.x",
         "renovate/eslint-3.x",
         "renovate/eslint-4.x",
         "renovate/chai-4.x",
         "renovate/istanbul-0.x",
         "renovate/mocha-2.x",
         "renovate/mocha-5.x"
       ],
       "deletedBranches": []
DEBUG: remainingBranches= (repository=LYNX/TestDep_F)
DEBUG: No branches to clean up (repository=LYNX/TestDep_F)
INFO: Renovate finished
```

**Comment by rarkins** [comment]
Yes, Renovate stops processing a repository after the first automerge. To automerge more than one, you need to run more than one.

The challenge to overcome is that once you merge into master branch, all other branches becomes temporarily unstable until GitHub calculates their mergeable status. You may have seen this in the web interface sometimes when it temporarily shows you a message like "Checking if this branch can be merged" after you update from master.

At one point, the Renovate CLI would restart itself after an automerge, but it still got caught up with the mergeable status problem so I added an arbitrary 5s sleep to mostly fix it. But then I found there was some kind of memory leak or state corruption happening only when we restarted like that, so I removed it.

The [Hosted app](https://github.com/apps/renovate) and [Pro](https://renovatebot.com/pro) versions don't need this anyway because they react to webhooks from GitHub, i.e. commits to the master `package.json` already result in a job being queued up behind the one in progress, so it doesn't matter if the current one exits early.

In the long run you may find this limitation to be fairly unimportant anyway, even with the CLI tool. Most users set Renovate to run at least once per hour, often more, and usually once you get on top of repositories then automerging 1 or more per hour is more than sufficient.
