### ISSUE TITLE
minor update in patch update branch

### ISSUE THREAD

**Issue by teppeis** [renovateapp/renovate#2011]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
In `renovate/renovate-12.21.x` branch, package.json was updated from `^12.21.16` to `^12.21.17`.
But package-lock.json was updated to `12.30.14`.

- https://github.com/teppeis/renovate-config/commit/adf001dd193542dbf39eec0425e565cb45aae20a#diff-32607347f8126e6534ebc7ebaec4853dL8420
- https://github.com/teppeis/renovate-config/compare/renovate/renovate-12.21.x
- https://renovatebot.com/dashboard#/repos/teppeis/renovate-config/jobs/8489449

**Expected behavior**
package-lock.json is updated to `12.21.17`.

**Additional context**
My config (only related part for this issue)
```
    "extends": [
      ":automergePatch",
      ":noUnscheduledUpdates",
      ":separatePatchReleases",
      ":unpublishSafe",
      "helpers:disableTypesNodeMajor"
    ],
    "upgradeInRange": true,
```

**Comment by rarkins** [comment]
This is a strange one and related to `upgradeInRange`.

`^12.21.16` to `^12.21.17` is indeed a "patch" update in the way we classify it. However the `latest` changed from 12.21.x to 12.30.x and so the lockfile with `12.30.14` is indeed valid - i.e. it's the correct lock file for that `package.json`.

Although I don't consider this a bug, I will leave this open in case I can think of any new ideas. I understand that it's undesirable that a minor update in the lock file is automerged as a patch, but that's the reality when your package.json effectively says "all versions 12.x are compatible". Ultimately if you want your lock file to be more predictable, you need to pin instead of use upgradeInRange.

Maybe one idea is that we consider these "in range" updates to be a different "type" of update to patch/minor/major, e.g. we class them type "bump" because it bumps the range. Then you could choose to automerge bumps (and take the risk they are minor updates) as a separate concept to automerging patches, although patches are only applicable if you have any pinned versions.

**Comment by rarkins** [comment]
@teppeis I thought of one more thing today - if you change to use tilde (`~`) ranges instead, then this problem would not occur either.

**Comment by rarkins** [comment]
Closing as I don’t intend to fix. Recommended to use pinned or tilde range instead.
