### ISSUE TITLE
Renovate fails to work on Gitlab CI

### ISSUE THREAD

**Issue by Nebulis** [renovateapp/renovate#2036]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
When running on our Gitlab CI through docker latest image (I can't tell for sure which image), Renovate fails to upgrade the second dependency. I noticed that failure twice. You can find the output of a run working and not working [here](gist.github.com/Nebulis/9284b85bde2af643d230ad6061badb90)

**To Reproduce**
I added in the [gist](https://gist.github.com/Nebulis/9284b85bde2af643d230ad6061badb90) bith renovate.json and gitlab-cy.yml file

**Additional context**
We use yarn. I thought it was related to #2010 because it ended up with the same kind of error: `INFO: Lock file error`. So I rollbacked to docker image 12.21.10 and it's working fine with exactly the same configuration

**Comment by rarkins** [comment]
Thanks for the detailed report. I note that it thanks for the detailed issue. I note:
- there was a npm backend error during lookups that maybe was just coincidental
- the yarn error happened on the second branch/run. Have you noticed if that’s the same pattern every time? It’s possible that the “find .” exceeds stdio on the second run due to too many files. I actually removed this today for a similar reason

**Comment by Nebulis** [comment]
- I think the npm backend error is coincidental, I didn't notice it in another failed job
- I noticed that pattern indeed
  - 1st upgrade OK
  - 2nd upgrade KO

I added to the gist another output (error-output-1) that is the output of the first failure I noticed. After this I tried to run locally to reproduce but everything went  fine. I rerun the pipeline again and then it again failed on the 2nd upgrade

**Comment by rarkins** [comment]
@Nebulis I see in the other one that there's also the "find ." output so it remains as my suspicion of the cause - which also means that the problem is already fixed. Can you try forcing `latest` docker image and see if the problem disappears? Best way to confirm it is if you have a run where you have 2 or more lock files generated and all are successful.

**Comment by Nebulis** [comment]
I will confirm as soon as I can make a run that need to upgrade 2+ dependencies. Thanks for your help anyway :+1:

**Comment by Nebulis** [comment]
Actually I played with the "recreateClosed" parameter to force the recreation of MR and it worked well. So I will close this issue and will keep an eye on it

Thanks :tada:
