### ISSUE TITLE
Dependency PR does not update yarn.lock

### ISSUE THREAD

**Issue by danez** [renovateapp/renovate#2108]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
https://github.com/researchgate/linting/pull/11 In this PR yarn.lock did not get updated.

**Expected behavior**
yarn lock should be regenerated.

**Additional context**
I'm confused about the statements in the docs about lock file maintenance., but as far as I understand my current config should create a PR once a month (which it didn't in june btw.) for patch and minor updates and also update yarn.lock when major versions get updated.

**Comment by rarkins** [comment]
Yes, PRs like this should normally have `yarn.lock` updated. I’ll take a look at logs for this PR as well as to see if there’s any indication for lock file maintenance.

**Comment by rarkins** [comment]
@danez the reason the PR was raised like this was because Renovate hasn't detected that your lerna repo uses `yarn` instead of `npm`. So it ran `lerna` using `npm`, which *generated* a new `package-lock.json`, which was then ignored because the bot was looking for an *updated* `yarn.lock`.

I took a look at your `lerna.json` and found that the `npmClient=yarn` setting was not present, but `useWorkspaces=true` was there. I updated Renovate's logic to use `yarn` if either of those fields are set, but I found that `lerna bootstrap` itself still detected `npm` and used it instead of `yarn`. Unless I'm missing something, it seems that the original Renovate logic was correct and `npmClient` must be set to `yarn` in `lerna.json`, so I have raised a PR for that to your repo: https://github.com/researchgate/linting/pull/12

Also something I noticed in the process was that the version of `lerna` declared in your `lerna.json` is `2.1.2` while in `devDependencies` it's `^2.5.1`. I assume they should be kept in sync (i.e. something Renovate could do but doesn't yet) although it's also unlikely to matter.

Please do this:
(1) Merge that PR, wait 15 minutes

If the `conventional-github-releaser` PR doesn't get automatically repaired/fixed (I suspect it won't because you're not configured to rebase all stale PRs), then do this:

(2) Rename the PR (e.g. to ".... - old")
(3) Close the PR

On the next Renovate run, it then should be fooled into thinking that PR never existed and create it fresh, hopefully with fixed lerna settings.

FYI the missing lock file maintenance support for `lerna` is a separate issue - #1974 - so you can Subscribe to that to track it.

**Comment by rarkins** [comment]
Please reopen this issue if it is not resolved after following the above steps

**Comment by danez** [comment]
ah that makes sense, the reason yarn client wasn't set  is because `lerna bootstrap` is never called as simply running yarn does all the bootstrapping, but it can't hurt to set it correctly. thanks

**Comment by rarkins** [comment]
FYI, we use the version defined in devDependencies to decide which `lerna` to spawn for each repo. 

I used to just run `yarn` too in cases like this but then realised maybe one day `lerna bootstrap` will do something additional or different, and then the bot would be sending wrong PRs, so it’s easiest to just call `lerna` every time.
