### ISSUE TITLE
New preset: apollo-client monorepo + react-apollo

### ISSUE THREAD

**Issue by astorije** [renovateapp/renovate#2120]
Hi there!

Today, the [`apollo-client` monorepo](https://github.com/apollographql/apollo-client) updated their packages, and we could see Renovate picking them up correctly. Later on, the [`react-apollo` repo/package](https://github.com/apollographql/react-apollo) was published, and again, Renovate picked it up just fine.
However, those were all depending on each other, so our 2 PRs failed, and needed to be combined.

Would you be open to a new preset that combines the Apollo packages mentioned above? If so, I would be happy to give it a shot :)

For context, we only extend the base config + rebaseStalePrs preset for now.

**Comment by rarkins** [comment]
Yes, this would be fine to add to the Renovate presets - although it would be in the https://github.com/renovatebot/presets repo rather than here.

Are you interested in combining *any* packages with `apollo` in the name, plus `graphql-client` from the `apollo-client` repo? Then the rule could look like this:

```
    "apolloAll": {
      "packageRules": [
        {
          "description": "Group packages from apolloclient monorepo together",
          "extends": "monorepo:apolloclient",
		  "packagePatterns": ["apollo"],
          "groupName": "apollo packages"
        }
      ]
    },
```

**Comment by astorije** [comment]
Argh @rarkins, I'm an idiot, sorry I opened noise in here! Do you need me to close this issue and open one in this other repo?

I think it would be rather dangerous to combine *all* repos with the word "apollo" in it, I would rather whitelist what Apollo themselves maintain.

I am adding this right now and trying to figure out where is the best place to do that, but I am confused about the [`group:apolloclientMonorepo` preset](https://renovatebot.com/docs/presets-group/#groupapolloclientmonorepo) and the [`monorepo:apolloclient` preset](https://renovatebot.com/docs/presets-monorepo/#monorepoapolloclient). It seems to me that [the former simply calls the latter](https://github.com/renovatebot/presets/blob/8bfad58b1966bb50b034ffd66075ee9c1c1d6e22/packages/renovate-config-group/package.json#L79-L87). What is the rationale behind this?

**Comment by rarkins** [comment]
The monorepo presets simply define _patterns_ to identify those. These can then be used in any type of rule, not just grouping. e.g. you could use the pattern to add automerge but not group. The group presets include a 1:1 mapping of monorepo definitions and groupings, so that for each monorepo definition we have you also have a group rules you can apply to put them in the same PR
