### ISSUE TITLE
Support semver range joins

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#687]
Currently Renovate does not support the ` || ` operator in dependencies. We also don't renovate peerDependencies for mostly the same reason.

**Comment by rarkins** [comment]
Here is an example use case of these in `dependencies`: https://github.com/apollographql/react-apollo/blob/master/package.json#L145
```
    "apollo-client": "^1.4.0 || ^2.0.0-0",
```

Using npm's semver calculator page we see this:
![image](https://user-images.githubusercontent.com/6311784/29444119-53140030-83dd-11e7-946c-034c457c834e.png)

This package presumably won't need an upgrade for a while, considering that 2.x is not even stable yet. The unstableness of `^2.0.0-0` also adds a challenge. Should it be maintained forever, or should this be switched to `^2.0.0` immediately after it becomes stable? And what if `3.0.0` is released - should the range be expanded to "^1.4.0 || ^2.0.0 || ^3.0.0"? Can we "simplify" such ranges, e.g. change it ourselves to be "1.4.0 - 3.x"? And what logic can renovate use to know this?

**Comment by rarkins** [comment]
The same apollo package also has `peerDependencies` like so:

```
  "peerDependencies": {
    "react": "0.14.x || 15.* || ^15.0.0 || ^16.0.0-alpha",
    "redux": "^2.0.0 || ^3.0.0"
  },
```

Let's say redux `4.0.0` is released. The most obvious update would be to `^2.0.0 || ^3.0.0 || ^4.0.0`. Or can we propose `2.x - 4.x`?

Then look at react. To show how challenging this can be, it appears that part of the existing semver is redundant: `15.* || ^15.0.0`

Here's the result:
![image](https://user-images.githubusercontent.com/6311784/29444310-d902cbb2-83de-11e7-8123-e593512d4527.png)

Similar question as earlier: once stable `16.0.0` is released, should the unstable support be removed? Would `0.14.x - 16.x` suffice?

**Comment by rarkins** [comment]
Merely *alerting* the user that their current range is "out of date" is probably the most important thing. Whether we get the exact semver to their liking or not is another. e.g. they may choose to drop support for old versions, like maybe react `0.14.x`

**Comment by rarkins** [comment]
Also this doesn't necessarily have to be restricted to only the case where the *existing* range has joins. If someone has `"tslint": "^5.5.0"` as existing `peerDependency` and `6.0.0` is released then they probably want the result to be `"tslint": "^5.5.0 || ^6.0.0"`

**Comment by rarkins** [comment]
@ikatyang I noticed that a lot of your repositories use `peerDependencies`, could you give your opinion on what would help you and any special cases you can think of?

**Comment by ikatyang** [comment]
The semver `||` in `dependencies` looks weird to me, if the newest version works fine why not just drop the old version?

For the peerDeps semver ranges, I'd prefer using single-direction range instead of joined range, which looks more intuitive to me, e.g. `"tslint": ">= 5.5.0"` instead of `"tslint": "^5.5.0 || ^6.0.0"`.

And I can't imagine why there're so many joined ranges in the above example:

```
"peerDependencies": {
  "react": "0.14.x || 15.* || ^15.0.0 || ^16.0.0-alpha",
  "redux": "^2.0.0 || ^3.0.0"
},
```

looks equivalent to

```
"peerDependencies": {
  "react": ">= 0.14.0 || ^16.0.0-alpha",
  "redux": ">= 2.0.0"
},
```

The only special case is the prerelease tag, npm (the one bundled with node v4, probably npm v2?) will throw errors for unmatched peerDeps, but yarn and newest npm will only throw warnings for unmatched peerDeps, which looks fine for those people who want to try out the prerelease version. (Prereleases looks dangerous to me, I won't use them unless there's bug fixes that I need, but once it got stable, I'll switch back to the stable version.)

An interesting repo that probably needs this feature can be found in [gulp-typescript](https://github.com/ivogabe/gulp-typescript), the TypeScript Team always [has to send a PR for their newer dev prerelease tag](https://github.com/ivogabe/gulp-typescript/pulls?utf8=%E2%9C%93&q=peer) so that their node v4 build won't break on travis.

---

Is it possible to not add the joined range but to redefine the semver range with the same meaning for those users? just like `"tslint": ">= 5.5.0"` vs `"tslint": "^5.5.0 || ^6.0.0"`.

**Comment by rarkins** [comment]
> The semver `||` in `dependencies` looks weird to me, if the newest version works fine why not just drop the old version?

I guess it's because some end users may be using the older version and it's to avoid duplicates.

> For the peerDeps semver ranges, I'd prefer using single-direction range instead of joined range, which looks more intuitive to me, e.g. `"tslint": ">= 5.5.0"` instead of `"tslint": "^5.5.0 || ^6.0.0"`.

Actually I don't like this approach, because it can easily lead to breaks. For example if version 7.x is released and breaks something then `"tslint": ">= 5.5.0"` will result in a build break while `"tslint": "^5.5.0 || ^6.0.0"` (or something equivalent) will not. So I think single-direction ranges shouldn't be used - needs an upper limit.

> (Prereleases looks dangerous to me, I won't use them unless there's bug fixes that I need, but once it got stable, I'll switch back to the stable version.)

Pre-releases usually have some type of semver value that makes the semver library classify them as "unstable", and Renovate defaults to stable only unless the *existing* value is unstable. So we're protected.

> An interesting repo that probably needs this feature can be found in [gulp-typescript](https://github.com/ivogabe/gulp-typescript), the TypeScript Team always [has to send a PR for their newer dev prerelease tag](https://github.com/ivogabe/gulp-typescript/pulls?utf8=%E2%9C%93&q=peer) so that their node v4 build won't break on travis.

That's a pretty strange example. Interesting that semver ignores unstable versions except the "current" unstable. All those `>=` seem unnecessary though.

> Is it possible to not add the joined range but to redefine the semver range with the same meaning for those users? just like `"tslint": ">= 5.5.0"` vs `"tslint": "^5.5.0 || ^6.0.0"`.

Yes, it's possible - although I've seen some people really like their existing semver approach kind of like how people like tabs vs spaces. So some would object to it. Also as mentioned above, I'd want an upper limit so something like `5.5 - 6.x`

**Comment by rarkins** [comment]
I'm going to downgrade this to pri3 because nobody is +1'ing it or adding comments, but I'd welcome ideas/examples on what we can implement.
