### ISSUE TITLE
Run on config file change

### ISSUE THREAD

**Issue by mbrevda** [renovateapp/renovate#880]
It would be helpful to get at least one run if the package.json/renovate.json changes. This would allow for instant testing of new configs!

**Comment by rarkins** [comment]
This requires Renovate to listen to webhooks from github/gitlab, which then also means it needs to run as a permanent service (rather than CLI tool). As such, it's out of the scope for Renovate itself (this repository) however I plan to implement it as part of RenovateApp (i.e. inbound webhooks trigger an extra run of Renovate for that repo). I will keep this issue open until that is completed, although don't expect any code to be added here.

**Comment by rarkins** [comment]
The Renovate App now runs immediately if any changes to `renovate.json` or `package.json` files are made. Also whenever any Renovate PRs are merged.
